'use strict';
// Aerospace medicine (m), aviation (a) and spaceflight (s) events by calendar day (MM-DD), for the "This day in history" card. Medicine events are
// listed first; each day has one to three events. Years are in y, never in the sentence. Checked by tools/test-onthisday.js.
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(); else root.OnThisDayData = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  return {
    "01-01": [{ y: 1914, k: "a", t: "The St. Petersburg-Tampa Airboat Line began operating, carrying a paying passenger on the first scheduled airline flight using a fixed-wing aircraft." },
      { y: 2019, k: "s", t: "New Horizons flew past the Kuiper belt object Arrokoth, the most distant object visited by a spacecraft at that time." }],
    "01-02": [{ y: 1959, k: "s", t: "The Soviet Union launched Luna 1, the first spacecraft to reach the vicinity of the Moon and enter heliocentric orbit." }],
    "01-03": [{ y: 2019, k: "s", t: "China's Chang'e 4 made the first soft landing on the far side of the Moon." }],
    "01-04": [{ y: 2004, k: "s", t: "The Mars Exploration Rover Spirit landed in Gusev crater." },
      { y: 1958, k: "s", t: "Sputnik 1 fell back into the atmosphere and burned up after about three months in orbit." }],
    "01-05": [{ y: 1972, k: "s", t: "President Nixon announced that NASA would develop the Space Shuttle." }],
    "01-06": [{ y: 1998, k: "s", t: "NASA launched Lunar Prospector on the evening of January 6, US time, a polar-orbiting probe that mapped the Moon's composition and gravity." }],
    "01-07": [{ y: 1785, k: "a", t: "Jean-Pierre Blanchard and John Jeffries made the first crossing of the English Channel by balloon." },
      { y: 1968, k: "s", t: "NASA launched Surveyor 7, the last of its lunar soft-landing probes." }],
    "01-08": [{ y: 1994, k: "m", t: "Physician-cosmonaut Valeri Polyakov launched on Soyuz TM-18 for a 14-month stay on Mir to study the effects of long spaceflight." },
      { y: 1944, k: "a", t: "The Lockheed XP-80, the first US jet fighter to reach production, made its first flight." }],
    "01-09": [{ y: 1793, k: "a", t: "Jean-Pierre Blanchard made the first balloon flight in North America, rising from Philadelphia." },
      { y: 1943, k: "a", t: "The Lockheed Constellation airliner made its first flight at Burbank, California." }],
    "01-10": [{ y: 1954, k: "a", t: "A BOAC de Havilland Comet broke up in flight near Elba; investigators later traced Comet failures to metal fatigue around the square windows." },
      { y: 1946, k: "s", t: "The US Army Signal Corps' Project Diana bounced radar signals off the Moon and detected the echoes." }],
    "01-11": [{ y: 1935, k: "a", t: "Amelia Earhart took off from Honolulu on the first solo flight from Hawaii to the mainland United States." }],
    "01-12": [{ y: 1986, k: "s", t: "Space Shuttle Columbia launched on STS-61-C with Representative Bill Nelson and Franklin Chang-Diaz aboard." },
      { y: 2005, k: "s", t: "NASA launched the Deep Impact spacecraft toward comet Tempel 1." }],
    "01-13": [{ y: 1942, k: "m", t: "Helmut Schenk ejected from a Heinkel He 280 jet after control loss from icing, the first emergency use of an ejection seat." },
      { y: 1982, k: "a", t: "Air Florida Flight 90 struck a bridge and crashed into the Potomac River after takeoff from Washington National Airport in icing conditions." }],
    "01-14": [{ y: 2005, k: "s", t: "The Huygens probe descended through Titan's atmosphere and landed on its surface." },
      { y: 1969, k: "s", t: "Soyuz 4 was launched, beginning the mission that achieved the first docking of two crewed spacecraft." }],
    "01-15": [{ y: 2006, k: "s", t: "The Stardust capsule returned to Earth carrying dust collected from comet Wild 2." },
      { y: 2009, k: "a", t: "US Airways Flight 1549 ditched in the Hudson River after bird strikes; all 155 people aboard survived." }],
    "01-16": [{ y: 2003, k: "s", t: "Space Shuttle Columbia launched on STS-107, its final mission." },
      { y: 1969, k: "s", t: "Soyuz 4 and Soyuz 5 docked in orbit, and two cosmonauts transferred between the craft by spacewalk." }],
    "01-17": [{ y: 1966, k: "a", t: "A B-52 and a KC-135 collided during refueling over Palomares, Spain, killing seven crew members and scattering weapon debris." },
      { y: 1969, k: "s", t: "Soyuz 4 landed, bringing Vladimir Shatalov home after the first docking with another crewed spacecraft." }],
    "01-18": [{ y: 1911, k: "a", t: "Eugene Ely landed a Curtiss biplane on a platform built on the cruiser USS Pennsylvania, the first landing on a ship." },
      { y: 2005, k: "a", t: "Airbus unveiled the A380 superjumbo at a ceremony in Toulouse." }],
    "01-19": [{ y: 2006, k: "s", t: "NASA launched New Horizons on its journey to Pluto." },
      { y: 1915, k: "a", t: "German Zeppelin airships carried out the first air raid on Britain, bombing towns on the Norfolk coast." }],
    "01-20": [{ y: 1992, k: "m", t: "Air Inter Flight 148 crashed near Strasbourg; investigators found the crew likely mis-set the autopilot descent mode, an example of mode confusion." },
      { y: 1978, k: "s", t: "The Soviet Union launched Progress 1, the first uncrewed cargo ship to resupply a space station." }],
    "01-21": [{ y: 1976, k: "a", t: "Concorde entered commercial service, with British Airways and Air France flights starting on the same day." }],
    "01-22": [{ y: 1970, k: "a", t: "A Pan Am Boeing 747 flew the first commercial 747 service, from New York to London." },
      { y: 1968, k: "s", t: "Apollo 5 launched and tested the lunar module in Earth orbit without a crew." }],
    "01-23": [{ y: 2009, k: "s", t: "Japan launched GOSAT, a satellite designed to monitor atmospheric greenhouse gases from orbit." }],
    "01-24": [{ y: 1986, k: "s", t: "Voyager 2 made its closest approach to Uranus, the first spacecraft flyby of the planet." },
      { y: 1978, k: "s", t: "The Soviet reconnaissance satellite Cosmos 954 reentered over northern Canada and scattered radioactive debris." }],
    "01-25": [{ y: 1984, k: "s", t: "President Reagan announced in his State of the Union address that NASA would build a permanently crewed space station." },
      { y: 1994, k: "s", t: "NASA and the Department of Defense launched the Clementine spacecraft to map the Moon." }],
    "01-26": [{ y: 1911, k: "a", t: "Glenn Curtiss flew his hydroaeroplane at San Diego, a successful practical seaplane flight in the United States." },
      { y: 1962, k: "s", t: "NASA launched Ranger 3, its first attempt at a lunar impact probe carrying instruments." }],
    "01-27": [{ y: 1967, k: "s", t: "A cabin fire during a launch rehearsal killed the Apollo 1 crew, Gus Grissom, Ed White and Roger Chaffee." }],
    "01-28": [{ y: 1986, k: "s", t: "Space Shuttle Challenger broke apart 73 seconds after liftoff, killing all seven crew members." }],
    "01-29": [{ y: 2016, k: "a", t: "The Boeing 737 MAX 8 made its first flight at Renton, Washington." }],
    "01-30": [{ y: 1948, k: "a", t: "Orville Wright died in Dayton, Ohio, at the age of 76." }],
    "01-31": [{ y: 1961, k: "m", t: "The chimpanzee Ham flew a suborbital flight on Mercury-Redstone 2 and performed lever tasks, helping show that humans could work in spaceflight." },
      { y: 1958, k: "s", t: "The United States launched Explorer 1, its first satellite, which detected the Van Allen radiation belts." },
      { y: 1971, k: "s", t: "Apollo 14 launched toward the Moon with Alan Shepard, Stuart Roosa and Edgar Mitchell." }],
    "02-01": [{ y: 2003, k: "s", t: "Space Shuttle Columbia broke apart during reentry over Texas, killing all seven crew members of STS-107." },
      { y: 2010, k: "s", t: "The US administration's budget proposal called for cancelling NASA's Constellation program." }],
    "02-02": [{ y: 1974, k: "a", t: "The General Dynamics YF-16 made its official first flight at Edwards Air Force Base." },
      { y: 1925, k: "a", t: "President Coolidge signed the Kelly Act, which let the Post Office contract private carriers to fly the mail." }],
    "02-03": [{ y: 1966, k: "s", t: "The Soviet Luna 9 probe made the first soft landing on the Moon and sent back images from the surface." },
      { y: 1995, k: "s", t: "Eileen Collins flew as pilot of Space Shuttle Discovery on STS-63, becoming the first woman to pilot a shuttle." }],
    "02-04": [{ y: 1993, k: "s", t: "Russia tested Znamya 2, a thin reflective sheet deployed from a Progress cargo ship to study sunlight reflection from orbit." }],
    "02-05": [{ y: 1987, k: "m", t: "Yuri Romanenko launched on Soyuz TM-2 for a 326-day Mir stay, then the longest spaceflight, providing long-duration physiological data." },
      { y: 1971, k: "s", t: "Apollo 14 landed in the Fra Mauro region, and Alan Shepard and Edgar Mitchell explored the surface." }],
    "02-06": [{ y: 2020, k: "m", t: "Christina Koch landed after 328 days on the ISS, the longest single spaceflight by a woman." },
      { y: 2018, k: "s", t: "SpaceX launched the first Falcon Heavy, sending a car toward a solar orbit." },
      { y: 1996, k: "a", t: "Birgenair Flight 301 crashed off the Dominican Republic after the crew misread airspeed indications caused by a blocked pitot tube." }],
    "02-07": [{ y: 1984, k: "s", t: "Bruce McCandless made the first untethered spacewalk using the Manned Maneuvering Unit on STS-41-B." },
      { y: 2008, k: "s", t: "Space Shuttle Atlantis launched on STS-122 to deliver the European Columbus laboratory to the ISS." }],
    "02-08": [{ y: 1974, k: "m", t: "The Skylab 4 crew splashed down after 84 days in orbit, ending the longest US mission to that date and its biomedical experiments." },
      { y: 2010, k: "a", t: "The Boeing 747-8 Freighter made its first flight." }],
    "02-09": [{ y: 1971, k: "m", t: "Apollo 14 returned to Earth; its crew was the last to undergo post-flight lunar quarantine, which NASA then dropped." },
      { y: 1969, k: "a", t: "The Boeing 747 made its first flight at Everett, Washington." },
      { y: 1963, k: "a", t: "The Boeing 727 made its first flight." }],
    "02-10": [{ y: 2009, k: "s", t: "An Iridium communications satellite and the defunct Russian Cosmos 2251 collided in orbit, producing thousands of debris fragments." }],
    "02-11": [{ y: 1970, k: "s", t: "Japan launched Ohsumi, its first satellite, becoming the fourth country to orbit a satellite on its own rocket." },
      { y: 1984, k: "s", t: "Space Shuttle Challenger landed at Kennedy Space Center, the first shuttle landing at the launch site." },
      { y: 2000, k: "s", t: "Space Shuttle Endeavour launched on STS-99 for the Shuttle Radar Topography Mission." }],
    "02-12": [{ y: 2009, k: "m", t: "Colgan Air Flight 3407 crashed near Buffalo after the crew responded improperly to a stall warning; crew fatigue was examined in the investigation." },
      { y: 2001, k: "s", t: "The NEAR Shoemaker spacecraft landed on asteroid Eros, the first landing on an asteroid." },
      { y: 1961, k: "s", t: "The Soviet Union launched Venera 1 toward Venus." }],
    "02-13": [{ y: 2012, k: "s", t: "The European Space Agency launched the first Vega rocket from French Guiana." }],
    "02-14": [{ y: 1990, k: "s", t: "Voyager 1 turned its camera back and took the family portrait of the Solar System that includes the Pale Blue Dot image of Earth." },
      { y: 2000, k: "s", t: "NEAR Shoemaker entered orbit around asteroid Eros, the first spacecraft to orbit an asteroid." }],
    "02-15": [{ y: 1961, k: "a", t: "Sabena Flight 548 crashed near Brussels, killing all 72 aboard, including the US figure skating team." }],
    "02-16": [{ y: 1998, k: "a", t: "China Airlines Flight 676 crashed while attempting to land at Taipei in bad weather, killing all aboard and several people on the ground." }],
    "02-17": [{ y: 1959, k: "s", t: "The United States launched Vanguard 2, its first weather satellite." },
      { y: 1996, k: "s", t: "NASA launched the NEAR spacecraft, the first mission of its Discovery program." }],
    "02-18": [{ y: 2021, k: "s", t: "NASA's Perseverance rover landed in Jezero crater on Mars." }],
    "02-19": [{ y: 1986, k: "s", t: "The Soviet Union launched the core module of the Mir space station." },
      { y: 1982, k: "a", t: "The Boeing 757 made its first flight." }],
    "02-20": [{ y: 1962, k: "s", t: "John Glenn flew Friendship 7 on the first US crewed orbital flight, completing three orbits." }],
    "02-21": [{ y: 1972, k: "s", t: "The Soviet Luna 20 probe landed in the lunar highlands and later returned a soil sample to Earth." }],
    "02-22": [{ y: 1987, k: "a", t: "The Airbus A320, the first airliner with digital fly-by-wire controls, made its first flight." }],
    "02-23": [{ y: 1909, k: "a", t: "J.A.D. McCurdy flew the Silver Dart at Baddeck, Nova Scotia, the first powered flight in Canada." }],
    "02-24": [{ y: 1949, k: "s", t: "A WAC Corporal atop a V-2 rocket, Bumper 5, reached about 390 km altitude over White Sands." },
      { y: 1989, k: "a", t: "A cargo door on United Airlines Flight 811 failed in flight, killing nine passengers." },
      { y: 2011, k: "s", t: "Space Shuttle Discovery launched on STS-133, its final flight." }],
    "02-25": [{ y: 1969, k: "s", t: "NASA launched Mariner 6 to fly past Mars." }],
    "02-26": [{ y: 1966, k: "s", t: "NASA launched AS-201, the first flight of the Saturn IB rocket and an uncrewed Apollo command module test." }],
    "02-27": [{ y: 2014, k: "s", t: "NASA and JAXA launched the Global Precipitation Measurement Core Observatory, on February 28 in Japan." }],
    "02-28": [{ y: 1959, k: "s", t: "The United States launched Discoverer 1, the first satellite intended for polar orbit." },
      { y: 1966, k: "s", t: "Astronauts Elliot See and Charles Bassett died when their T-38 jet crashed in bad weather at St. Louis." }],
    "02-29": [{ y: 1996, k: "a", t: "A Faucett Peru Boeing 737 crashed on approach to Arequipa, Peru, killing all 123 people aboard." }],
    "03-01": [{ y: 2016, k: "m", t: "Scott Kelly returned from a year on the ISS, enabling comparison studies with his twin brother Mark." },
      { y: 1912, k: "a", t: "Albert Berry made the first parachute jump from a powered airplane, over Kinloch Field near St. Louis." }],
    "03-02": [{ y: 1969, k: "a", t: "The French Concorde 001 prototype made its first flight at Toulouse." },
      { y: 1978, k: "s", t: "Soyuz 28 launched with Vladimir Remek, the first person in space who was neither Soviet nor American." },
      { y: 2004, k: "s", t: "The European Space Agency launched the Rosetta probe toward comet 67P." }],
    "03-03": [{ y: 1915, k: "a", t: "Congress created the National Advisory Committee for Aeronautics, the predecessor of NASA." },
      { y: 1969, k: "s", t: "Apollo 9 launched on the first crewed flight of the lunar module in Earth orbit." },
      { y: 1974, k: "a", t: "Turkish Airlines Flight 981 crashed near Paris after a rear cargo door failed, killing all 346 aboard." }],
    "03-04": [{ y: 1954, k: "a", t: "The Lockheed XF-104 Starfighter made its first flight at Edwards Air Force Base." },
      { y: 1966, k: "a", t: "A Canadian Pacific DC-8 crashed on landing at Tokyo's Haneda Airport in poor visibility, killing 64 people." }],
    "03-05": [{ y: 1936, k: "a", t: "The prototype Supermarine Spitfire made its first flight." },
      { y: 1979, k: "s", t: "Voyager 1 made its closest approach to Jupiter." },
      { y: 1966, k: "a", t: "BOAC Flight 911 broke apart in severe turbulence near Mount Fuji, Japan, killing all 124 aboard." }],
    "03-06": [{ y: 1986, k: "s", t: "The Soviet Vega 1 probe flew past Halley's Comet and returned images of the nucleus region." },
      { y: 1969, k: "s", t: "Russell Schweickart performed a spacewalk testing the Apollo portable life support system during Apollo 9." }],
    "03-07": [{ y: 1969, k: "s", t: "On Apollo 9, the lunar module Spider flew apart from the command module and then rendezvoused and docked with it." }],
    "03-08": [{ y: 1910, k: "a", t: "Raymonde de Laroche became the first woman to receive a pilot's license, issued by the Aero-Club de France." },
      { y: 2014, k: "a", t: "Malaysia Airlines Flight 370 disappeared during a flight from Kuala Lumpur to Beijing with 239 people aboard." }],
    "03-09": [{ y: 1961, k: "m", t: "Sputnik 9 carried the dog Chernushka and a mannequin on a one-orbit test flight, a final check before the first human spaceflight." },
      { y: 2011, k: "s", t: "Space Shuttle Discovery landed at Kennedy Space Center, ending its final mission and 39th flight." }],
    "03-10": [{ y: 1977, k: "s", t: "Astronomers aboard NASA's Kuiper Airborne Observatory discovered the rings of Uranus." },
      { y: 2006, k: "s", t: "The Mars Reconnaissance Orbiter entered orbit around Mars." },
      { y: 2019, k: "a", t: "Ethiopian Airlines Flight 302, a Boeing 737 MAX 8, crashed shortly after takeoff from Addis Ababa, killing all 157 aboard." }],
    "03-11": [{ y: 1960, k: "s", t: "NASA launched Pioneer 5, which returned data on interplanetary space between Earth and Venus." }],
    "03-12": [{ y: 2008, k: "s", t: "Cassini flew about 50 km above Enceladus and sampled the plumes of water vapor and ice venting from its south pole." }],
    "03-13": [{ y: 1969, k: "s", t: "Apollo 9 splashed down in the Atlantic after ten days, completing the first crewed test of the lunar module." },
      { y: 2019, k: "a", t: "The US Federal Aviation Administration grounded Boeing 737 MAX aircraft after two fatal crashes." }],
    "03-14": [{ y: 2019, k: "m", t: "Christina Koch launched to the ISS for an extended stay that contributed to data on long-duration spaceflight in women." },
      { y: 1995, k: "s", t: "Norman Thagard, a physician, launched on Soyuz TM-21 to become the first American to live aboard the Mir space station." },
      { y: 1986, k: "s", t: "The European Giotto probe passed within about 600 km of the nucleus of Halley's Comet." }],
    "03-15": [{ y: 2009, k: "s", t: "Space Shuttle Discovery launched on STS-119 to install the final pair of solar arrays on the ISS." }],
    "03-16": [{ y: 1926, k: "s", t: "Robert Goddard launched the first liquid-fueled rocket at Auburn, Massachusetts." },
      { y: 1966, k: "s", t: "Gemini 8 launched and made the first docking of two spacecraft, then a stuck thruster forced an early return." }],
    "03-17": [{ y: 1958, k: "s", t: "The United States launched Vanguard 1, the oldest artificial satellite still in orbit." }],
    "03-18": [{ y: 1965, k: "m", t: "Alexei Leonov made the first spacewalk; his suit ballooned in vacuum, and he had to bleed off pressure to re-enter the airlock." },
      { y: 1980, k: "s", t: "A Vostok rocket exploded during fueling at Plesetsk, killing about 48 people." }],
    "03-19": [{ y: 1965, k: "s", t: "Voskhod 2 landed far off target in the Ural forest after a manual reentry, and the crew waited for rescue overnight." },
      { y: 2016, k: "a", t: "Flydubai Flight 981 crashed at Rostov-on-Don during a go-around in bad weather, killing all 62 aboard." }],
    "03-20": [{ y: 1999, k: "a", t: "Bertrand Piccard and Brian Jones in the Breitling Orbiter 3 crossed the longitude of their departure over Mauritania, completing the first nonstop balloon flight around the world." }],
    "03-21": [{ y: 1946, k: "a", t: "The US Army Air Forces created Strategic Air Command, Air Defense Command and Tactical Air Command." }],
    "03-22": [{ y: 1995, k: "m", t: "Physician-cosmonaut Valeri Polyakov returned to Earth after 437 days aboard Mir, the longest single spaceflight to date." },
      { y: 1996, k: "s", t: "Shannon Lucid launched on STS-76 to Mir, beginning a stay that set a US record for a woman." }],
    "03-23": [{ y: 1965, k: "s", t: "Gemini 3 launched with Gus Grissom and John Young on the first crewed Gemini flight." },
      { y: 2001, k: "s", t: "The Mir space station was deorbited and fell into the South Pacific." }],
    "03-24": [{ y: 2015, k: "m", t: "Germanwings Flight 9525 crashed in the French Alps; investigators found the co-pilot, who had a psychiatric condition, deliberately descended the aircraft." },
      { y: 1965, k: "s", t: "Ranger 9 transmitted live images as it crashed into the Moon." },
      { y: 1961, k: "s", t: "Mercury-Redstone BD flew a final suborbital test before the first US crewed spaceflight." }],
    "03-25": [{ y: 1961, k: "m", t: "Sputnik 10 carried the dog Zvezdochka and a mannequin on a one-orbit flight in the last test before Gagarin's flight." }],
    "03-26": [{ y: 1958, k: "s", t: "The United States launched Explorer 3, which confirmed the Van Allen radiation belts." }],
    "03-27": [{ y: 2015, k: "m", t: "Scott Kelly and Mikhail Kornienko launched to the ISS for a one-year mission that included extensive physiological study." },
      { y: 1977, k: "a", t: "Two Boeing 747s collided on a runway at Tenerife, killing 583 people in the deadliest accident in aviation history." },
      { y: 1968, k: "s", t: "Yuri Gagarin and flight instructor Vladimir Seryogin died in a MiG-15UTI crash near Moscow." }],
    "03-28": [{ y: 1910, k: "a", t: "Henri Fabre made the first flight of a powered seaplane, taking off from water at Martigues, France." }],
    "03-29": [{ y: 1974, k: "s", t: "Mariner 10 made the first spacecraft flyby of Mercury." }],
    "03-30": [{ y: 2006, k: "s", t: "Soyuz TMA-8 launched with Marcos Pontes, the first Brazilian astronaut, to the ISS." }],
    "03-31": [{ y: 1966, k: "s", t: "The Soviet Union launched Luna 10, the first spacecraft to orbit the Moon." },
      { y: 1931, k: "a", t: "TWA Flight 599 crashed in Kansas, killing Notre Dame coach Knute Rockne; the wooden wing failure prompted tighter aircraft regulation." }],
    "04-01": [{ y: 1918, k: "a", t: "The Royal Air Force was formed by merging the Royal Flying Corps and the Royal Naval Air Service." },
      { y: 1960, k: "s", t: "TIROS-1, the first successful weather satellite, was launched from Cape Canaveral." }],
    "04-02": [{ y: 1958, k: "s", t: "President Eisenhower sent Congress a special message proposing a civilian space agency built on the NACA, which led to the creation of NASA." }],
    "04-03": [{ y: 1933, k: "a", t: "The Houston-Mount Everest Flight Expedition flew two aircraft over the summit of Mount Everest for the first time." },
      { y: 1973, k: "s", t: "The Soviet Union launched the Salyut 2 space station." }],
    "04-04": [{ y: 1983, k: "s", t: "Space Shuttle Challenger made its first launch, on mission STS-6." }],
    "04-05": [{ y: 1990, k: "s", t: "The Pegasus rocket made its first flight, launched from a NASA B-52 carrier aircraft as the first air-launched orbital rocket." }],
    "04-06": [{ y: 1973, k: "s", t: "NASA launched Pioneer 11, which later became the second spacecraft to fly past Jupiter and the first to visit Saturn." }],
    "04-07": [{ y: 1983, k: "s", t: "Story Musgrave and Donald Peterson made the first spacewalk of the Space Shuttle program during STS-6." }],
    "04-08": [{ y: 1964, k: "s", t: "The first Gemini spacecraft, Gemini 1, was launched uncrewed on a Titan II rocket to test the vehicle." }],
    "04-09": [{ y: 1959, k: "s", t: "NASA introduced its first astronaut group, the seven Mercury astronauts, selected after extensive medical and psychological screening." }],
    "04-10": [{ y: 1979, k: "s", t: "Soyuz 33 was launched toward the Salyut 6 station with a Soviet and a Bulgarian cosmonaut aboard." }],
    "04-11": [{ y: 1970, k: "s", t: "Apollo 13 was launched toward the Moon with Lovell, Swigert and Haise." }],
    "04-12": [{ y: 1961, k: "s", t: "Yuri Gagarin made the first human spaceflight, completing a single orbit of Earth aboard Vostok 1." },
      { y: 1981, k: "s", t: "Space Shuttle Columbia made the first orbital flight of the Shuttle program, on mission STS-1." }],
    "04-13": [{ y: 1970, k: "s", t: "An oxygen tank ruptured aboard Apollo 13 on the way to the Moon, forcing the crew to abandon the landing." }],
    "04-14": [{ y: 1981, k: "s", t: "Columbia landed at Edwards Air Force Base, completing STS-1, the first Space Shuttle flight." }],
    "04-15": [{ y: 1952, k: "a", t: "The Boeing YB-52 Stratofortress prototype made its first flight." }],
    "04-16": [{ y: 1972, k: "s", t: "Apollo 16, carrying Young, Mattingly and Duke, was launched toward the Moon." }],
    "04-17": [{ y: 1998, k: "m", t: "Space Shuttle Columbia launched the Neurolab mission, STS-90, a Spacelab flight dedicated to studying the nervous system in weightlessness." },
      { y: 1970, k: "s", t: "The Apollo 13 crew splashed down safely in the Pacific Ocean after their aborted lunar mission." }],
    "04-18": [{ y: 1942, k: "a", t: "Sixteen B-25 bombers led by James Doolittle launched from the carrier USS Hornet to attack Japan." }],
    "04-19": [{ y: 1971, k: "s", t: "The Soviet Union launched Salyut 1, the first space station." }],
    "04-20": [{ y: 2023, k: "s", t: "SpaceX flew the first integrated test flight of its Starship and Super Heavy vehicle from Texas." }],
    "04-21": [{ y: 1944, k: "m", t: "Lt. Carter Harman began the first helicopter combat rescue, flying a YR-4 in Burma to recover a downed pilot and wounded British soldiers." }],
    "04-22": [{ y: 2010, k: "s", t: "The U.S. Air Force launched the first X-37B orbital test vehicle on an Atlas V rocket." }],
    "04-23": [{ y: 2021, k: "s", t: "SpaceX launched Crew-2, carrying four astronauts to the International Space Station on a reused Crew Dragon and Falcon 9 booster." }],
    "04-24": [{ y: 1967, k: "s", t: "Soyuz 1 crashed on landing after its parachute system failed, killing cosmonaut Vladimir Komarov." },
      { y: 1990, k: "s", t: "Space Shuttle Discovery launched on STS-31 carrying the Hubble Space Telescope." }],
    "04-25": [{ y: 1990, k: "s", t: "The Hubble Space Telescope was deployed from Space Shuttle Discovery." },
      { y: 2002, k: "s", t: "Mark Shuttleworth launched on Soyuz TM-34 as a paying participant and visited the International Space Station." }],
    "04-26": [{ y: 1962, k: "s", t: "Ariel 1, the first British satellite, was launched on a Thor-Delta rocket from Cape Canaveral." },
      { y: 1993, k: "s", t: "Space Shuttle Columbia launched on STS-55, the German Spacelab D-2 mission." }],
    "04-27": [{ y: 2022, k: "s", t: "SpaceX launched Crew-4 to the International Space Station." }],
    "04-28": [{ y: 2001, k: "s", t: "Dennis Tito launched on Soyuz TM-32 and became the first paying space tourist to visit the International Space Station." }],
    "04-29": [{ y: 1988, k: "a", t: "The Boeing 747-400 made its first flight." },
      { y: 2013, k: "a", t: "Virgin Galactic's SpaceShipTwo made its first powered flight." }],
    "04-30": [{ y: 2001, k: "s", t: "Soyuz TM-32 docked with the International Space Station, bringing Dennis Tito aboard." }],
    "05-01": [{ y: 1960, k: "a", t: "A Soviet missile shot down a U.S. Lockheed U-2 flown by Francis Gary Powers over the Soviet Union." }],
    "05-02": [{ y: 1952, k: "a", t: "BOAC began the first scheduled jet airliner service, flying the de Havilland Comet from London to Johannesburg." }],
    "05-03": [{ y: 1923, k: "a", t: "Oakley Kelly and John Macready completed the first nonstop flight across the United States in a Fokker T-2." },
      { y: 1952, k: "a", t: "A U.S. Air Force C-47 carrying Col. William Benedict and Lt. Col. Joseph Fletcher made the first landing at the North Pole." }],
    "05-04": [{ y: 1989, k: "s", t: "Space Shuttle Atlantis launched the Magellan probe to Venus on mission STS-30." }],
    "05-05": [{ y: 1961, k: "s", t: "Alan Shepard became the first American in space, flying a suborbital trajectory in Mercury Freedom 7." }],
    "05-06": [{ y: 1937, k: "a", t: "The airship Hindenburg caught fire and was destroyed while landing at Lakehurst, New Jersey." }],
    "05-07": [{ y: 1992, k: "s", t: "Space Shuttle Endeavour made its first flight, on mission STS-49." }],
    "05-08": [{ y: 1935, k: "a", t: "Amelia Earhart flew nonstop from Mexico City to Newark, New Jersey." }],
    "05-09": [{ y: 2003, k: "s", t: "Japan launched the Hayabusa spacecraft to collect a sample from the asteroid Itokawa." }],
    "05-10": [{ y: 1972, k: "a", t: "The Fairchild Republic A-10 Thunderbolt II made its first flight." }],
    "05-11": [{ y: 2009, k: "s", t: "Space Shuttle Atlantis launched on STS-125, the final servicing mission to the Hubble Space Telescope." },
      { y: 1881, k: "a", t: "Theodore von Karman, who became a leading aerodynamicist, was born in Budapest." }],
    "05-12": [{ y: 1926, k: "a", t: "The airship Norge, with Roald Amundsen and Umberto Nobile aboard, flew over the North Pole." }],
    "05-13": [{ y: 1940, k: "a", t: "Igor Sikorsky made the first free flight of the VS-300, his prototype single-rotor helicopter." }],
    "05-14": [{ y: 1973, k: "s", t: "NASA launched Skylab, its first space station, on the last Saturn V." }],
    "05-15": [{ y: 1963, k: "m", t: "Gordon Cooper launched on Mercury-Atlas 9 for a 22-orbit flight of about 34 hours, after which he showed orthostatic intolerance." }],
    "05-16": [{ y: 2011, k: "s", t: "Space Shuttle Endeavour launched on STS-134, its final mission, delivering the Alpha Magnetic Spectrometer to the International Space Station." }],
    "05-17": [{ y: 1946, k: "a", t: "The Douglas XB-43 Jetmaster, an early American jet bomber prototype, made its first flight." }],
    "05-18": [{ y: 1969, k: "s", t: "Apollo 10 was launched on the full dress rehearsal for the first lunar landing." }],
    "05-19": [{ y: 1996, k: "s", t: "Space Shuttle Endeavour launched on STS-77, carrying the Spacehab module and the Spartan satellite." }],
    "05-20": [{ y: 1927, k: "a", t: "Charles Lindbergh took off from Roosevelt Field, New York, in the Spirit of St. Louis on his solo flight to Paris." }],
    "05-21": [{ y: 1927, k: "a", t: "Charles Lindbergh landed at Le Bourget near Paris, completing the first solo nonstop transatlantic flight." }],
    "05-22": [{ y: 1906, k: "a", t: "The Wright brothers were granted U.S. patent 821,393 for their flying machine." },
      { y: 1969, k: "s", t: "Apollo 10's lunar module descended to within about 15 kilometers of the lunar surface in a rehearsal for the landing." }],
    "05-23": [{ y: 1848, k: "a", t: "Otto Lilienthal, who made the first well-documented repeated glider flights, was born in Anklam, Prussia." }],
    "05-24": [{ y: 1962, k: "s", t: "Scott Carpenter flew three orbits of Earth in the Mercury capsule Aurora 7." }],
    "05-25": [{ y: 1973, k: "m", t: "Skylab 2, the first crew to occupy the station, launched with physician Joseph Kerwin, Charles Conrad and Paul Weitz." },
      { y: 1961, k: "s", t: "President Kennedy told Congress the United States should land a man on the Moon and return him safely before the decade ended." }],
    "05-26": [{ y: 1969, k: "s", t: "The Apollo 10 crew splashed down in the Pacific Ocean after their lunar orbit mission." }],
    "05-27": [{ y: 1931, k: "m", t: "Auguste Piccard and Paul Kipfer reached about 15,800 meters in a sealed pressurized gondola, becoming the first people to enter the stratosphere." }],
    "05-28": [{ y: 1959, k: "m", t: "The monkeys Able and Baker were launched on a Jupiter missile and recovered alive, a U.S. biomedical test of spaceflight." }],
    "05-29": [{ y: 1940, k: "a", t: "The prototype Vought F4U Corsair made its first flight." }],
    "05-30": [{ y: 1949, k: "m", t: "Test pilot Jo Lancaster made the first emergency ejection from a British aircraft with a Martin-Baker seat, leaving an Armstrong Whitworth AW.52." },
      { y: 1966, k: "s", t: "NASA launched Surveyor 1, its first lunar soft-landing spacecraft." }],
    "05-31": [{ y: 1928, k: "a", t: "Charles Kingsford Smith and his crew left Oakland, California, in the Southern Cross on the first flight across the Pacific to Australia." },
      { y: 2008, k: "s", t: "Space Shuttle Discovery launched on STS-124, carrying Japan's Kibo laboratory module to the International Space Station." }],
    "06-01": [{ y: 1970, k: "m", t: "Soyuz 9 launched with Andriyan Nikolayev and Vitaly Sevastyanov for an 18-day flight that set a new endurance record and included physiological studies." }],
    "06-02": [{ y: 1957, k: "m", t: "Capt. Joseph Kittinger rose in a sealed Manhigh I balloon gondola to about 95,000 feet, studying human factors for spaceflight." },
      { y: 1966, k: "s", t: "Surveyor 1 made the first U.S. soft landing on the Moon." }],
    "06-03": [{ y: 1965, k: "s", t: "Gemini 4 launched, and Ed White later became the first American to walk in space." }],
    "06-04": [{ y: 1783, k: "a", t: "The Montgolfier brothers gave the first public demonstration of their hot-air balloon at Annonay, France." },
      { y: 1996, k: "s", t: "The first Ariane 5 rocket broke up shortly after liftoff from Kourou, French Guiana." }],
    "06-05": [{ y: 1991, k: "m", t: "Space Shuttle Columbia launched on STS-40, Spacelab Life Sciences 1, the first Spacelab mission devoted entirely to life sciences." }],
    "06-06": [{ y: 1944, k: "a", t: "Allied airborne forces landed in Normandy by parachute and glider in the opening phase of the D-Day invasion." },
      { y: 1971, k: "s", t: "Soyuz 11 launched to the Salyut 1 space station with Dobrovolsky, Volkov and Patsayev." }],
    "06-07": [{ y: 1971, k: "s", t: "Soyuz 11 docked with Salyut 1, and the crew became the first to occupy a space station." },
      { y: 1965, k: "s", t: "Gemini 4 landed in the Atlantic after about four days in orbit." }],
    "06-08": [{ y: 1959, k: "a", t: "The North American X-15 made its first flight, an unpowered glide after release from a B-52." },
      { y: 1966, k: "a", t: "An XB-70 Valkyrie collided with an F-104 during a formation flight over California, destroying both aircraft." }],
    "06-09": [{ y: 1928, k: "a", t: "Charles Kingsford Smith and his crew landed the Southern Cross at Brisbane, completing the first trans-Pacific flight." }],
    "06-10": [{ y: 1990, k: "m", t: "A cockpit windscreen blew out on British Airways Flight 5390 and the captain was partly pulled out; the first officer landed the aircraft safely." }],
    "06-11": [{ y: 1926, k: "a", t: "The Ford Trimotor, an early all-metal airliner, made its first flight." }],
    "06-12": [{ y: 1979, k: "a", t: "Bryan Allen crossed the English Channel in the human-powered Gossamer Albatross." }],
    "06-13": [{ y: 1983, k: "s", t: "Pioneer 10 crossed the orbit of Neptune, the first spacecraft to pass beyond the orbits of the known planets." }],
    "06-14": [{ y: 1949, k: "m", t: "Albert II, a rhesus monkey, flew on a V-2 rocket to about 134 kilometers, becoming the first primate in space; he died when the parachute failed." },
      { y: 1919, k: "a", t: "John Alcock and Arthur Brown took off from Newfoundland on the first nonstop transatlantic flight." },
      { y: 1963, k: "s", t: "Valery Bykovsky launched on Vostok 5 for a flight of nearly five days." }],
    "06-15": [{ y: 1898, k: "m", t: "Hubertus Strughold, a German-American physician and a founder of space medicine, was born." },
      { y: 1919, k: "a", t: "Alcock and Brown landed in a bog at Clifden, Ireland, completing the first nonstop transatlantic flight." }],
    "06-16": [{ y: 1963, k: "s", t: "Valentina Tereshkova launched on Vostok 6 and became the first woman in space." }],
    "06-17": [{ y: 1928, k: "a", t: "Amelia Earhart left Newfoundland aboard the Friendship, becoming the first woman to cross the Atlantic by air as a passenger." }],
    "06-18": [{ y: 1983, k: "s", t: "Sally Ride launched on STS-7 and became the first American woman in space." }],
    "06-19": [{ y: 1970, k: "m", t: "Soyuz 9 landed after nearly 18 days, and the crew needed time to readapt to gravity afterward." }],
    "06-20": [{ y: 1944, k: "s", t: "A German V-2 rocket test flight reached about 175 kilometers, the first human-made object to reach space." }],
    "06-21": [{ y: 2004, k: "s", t: "SpaceShipOne, flown by Mike Melvill, made the first privately funded crewed spaceflight." }],
    "06-22": [{ y: 1973, k: "m", t: "The Skylab 2 crew splashed down after 28 days, the longest U.S. spaceflight up to that time, and medical tests compared them with preflight baselines." }],
    "06-23": [{ y: 1931, k: "a", t: "Wiley Post and Harold Gatty left Roosevelt Field, New York, on a round-the-world flight in the Winnie Mae." }],
    "06-24": [{ y: 1943, k: "m", t: "Dr. William Randolph Lovelace II parachuted from about 40,000 feet in a test of high-altitude oxygen equipment, a record at that time." },
      { y: 1983, k: "s", t: "Space Shuttle Challenger landed at Edwards Air Force Base, ending the STS-7 mission with Sally Ride aboard." }],
    "06-25": [{ y: 1997, k: "s", t: "An uncrewed Progress cargo ship collided with the Mir space station during a docking test, damaging the Spektr module." }],
    "06-26": [{ y: 1948, k: "a", t: "U.S. Air Force transports began flights to supply West Berlin, the start of the Berlin Airlift." }],
    "06-27": [{ y: 1978, k: "s", t: "Soyuz 30 launched to Salyut 6 with Soviet and Polish cosmonauts aboard." }],
    "06-28": [{ y: 1927, k: "a", t: "Albert Hegenberger and Lester Maitland completed the first flight from California to Hawaii." }],
    "06-29": [{ y: 1995, k: "s", t: "Space Shuttle Atlantis docked with the Mir space station on STS-71, the first shuttle-Mir docking." }],
    "06-30": [{ y: 1971, k: "m", t: "The Soyuz 11 crew died during reentry when the capsule lost pressure, killing Dobrovolsky, Volkov and Patsayev." }],
    "07-01": [{ y: 1931, k: "a", t: "Wiley Post and Harold Gatty landed back at Roosevelt Field in New York, completing a round-the-world flight in under nine days." }],
    "07-02": [{ y: 1900, k: "a", t: "The first Zeppelin airship, LZ 1, made its maiden flight over Lake Constance." },
      { y: 1937, k: "a", t: "Amelia Earhart and navigator Fred Noonan disappeared over the Pacific during an attempted round-the-world flight." }],
    "07-03": [{ y: 1969, k: "s", t: "The Soviet N1 Moon rocket exploded just after liftoff from Baikonur, destroying its launch complex." }],
    "07-04": [{ y: 1982, k: "s", t: "Space Shuttle Columbia landed at Edwards Air Force Base, ending STS-4, the final test flight of the shuttle program." },
      { y: 1997, k: "s", t: "Mars Pathfinder landed on Mars and later deployed the Sojourner rover." },
      { y: 2005, k: "s", t: "The impactor from NASA's Deep Impact probe struck comet Tempel 1." }],
    "07-05": [{ y: 2016, k: "s", t: "NASA's Juno spacecraft completed its engine burn and entered orbit around Jupiter on the evening of July 4, US time, the second spacecraft to do so." }],
    "07-06": [{ y: 1919, k: "a", t: "The British airship R34 landed at Long Island, completing the first east-to-west crossing of the Atlantic by air." }],
    "07-07": [{ y: 1946, k: "a", t: "Howard Hughes was seriously injured when the experimental XF-11 reconnaissance aircraft crashed in Beverly Hills during a test flight." }],
    "07-08": [{ y: 2011, k: "s", t: "Atlantis lifted off on STS-135, the last flight of the Space Shuttle program." }],
    "07-09": [{ y: 1979, k: "s", t: "Voyager 2 made its closest approach to Jupiter." },
      { y: 1982, k: "a", t: "Pan Am Flight 759, a Boeing 727, crashed after takeoff from New Orleans in a microburst wind shear event." }],
    "07-10": [{ y: 1938, k: "a", t: "Howard Hughes took off from New York on a round-the-world flight that he completed in just over three days." },
      { y: 1962, k: "s", t: "Telstar 1, the first active communications satellite, was launched." }],
    "07-11": [{ y: 1979, k: "s", t: "Skylab, the first US space station, reentered the atmosphere and broke up over the Indian Ocean and Western Australia." },
      { y: 2019, k: "s", t: "Hayabusa2 made a second touchdown on asteroid Ryugu to collect subsurface material." }],
    "07-12": [{ y: 2000, k: "s", t: "The Zvezda service module was launched, providing the first living quarters and core systems for the International Space Station." },
      { y: 2022, k: "s", t: "NASA released the first full-color science images from the James Webb Space Telescope." }],
    "07-13": [{ y: 1969, k: "s", t: "The Soviet Luna 15 probe was launched toward the Moon three days before Apollo 11." }],
    "07-14": [{ y: 2015, k: "s", t: "New Horizons made its closest approach to Pluto, the first flyby of the dwarf planet." },
      { y: 2023, k: "s", t: "India launched Chandrayaan-3 toward the Moon." }],
    "07-15": [{ y: 1954, k: "a", t: "The Boeing 367-80, prototype of the 707, made its first flight at Renton, Washington." },
      { y: 1975, k: "s", t: "Apollo and Soyuz spacecraft were launched for the Apollo-Soyuz Test Project, the first joint US-Soviet crewed mission." }],
    "07-16": [{ y: 1969, k: "s", t: "Apollo 11 lifted off from Kennedy Space Center carrying Armstrong, Aldrin and Collins to the Moon." },
      { y: 1994, k: "s", t: "The first fragment of comet Shoemaker-Levy 9 struck Jupiter." }],
    "07-17": [{ y: 1962, k: "a", t: "X-15 pilot Robert White flew to an altitude of about 314,750 feet, which earned him USAF astronaut wings." },
      { y: 1975, k: "s", t: "Apollo and Soyuz docked in Earth orbit, and the crews met in the first international crewed link-up." },
      { y: 1996, k: "a", t: "TWA Flight 800, a Boeing 747, exploded and crashed into the Atlantic off Long Island shortly after departure from New York." }],
    "07-18": [{ y: 1938, k: "a", t: "Douglas Corrigan landed in Dublin after a flight from New York, having filed a plan to fly to California." },
      { y: 1966, k: "s", t: "Gemini 10 launched and made two rendezvous with Agena target vehicles during a three-day mission." }],
    "07-19": [{ y: 1963, k: "a", t: "X-15 pilot Joseph Walker flew to about 106 kilometers, an altitude above the international space boundary of 100 km." },
      { y: 1989, k: "a", t: "United Airlines Flight 232 crash-landed at Sioux City, Iowa, after an engine failure destroyed its hydraulic systems." }],
    "07-20": [{ y: 1969, k: "s", t: "The Apollo 11 lunar module Eagle landed on the Moon in the Sea of Tranquility." },
      { y: 1976, k: "s", t: "Viking 1 landed on Mars, the first successful US Mars lander." }],
    "07-21": [{ y: 1961, k: "s", t: "Gus Grissom's Mercury capsule Liberty Bell 7 sank after its hatch blew off following splashdown, and he was recovered from the water." },
      { y: 2011, k: "s", t: "Atlantis landed at Kennedy Space Center, ending the final Space Shuttle mission." }],
    "07-22": [{ y: 1951, k: "m", t: "Soviet dogs Dezik and Tsygan flew on a suborbital rocket to about 100 km altitude and were recovered alive." },
      { y: 1933, k: "a", t: "Wiley Post returned to New York, completing the first solo flight around the world." },
      { y: 1962, k: "s", t: "Mariner 1, the first US Venus probe, was launched and then destroyed by range safety after veering off course." }],
    "07-23": [{ y: 1972, k: "s", t: "Landsat 1, the first Earth resources satellite, was launched." },
      { y: 1983, k: "a", t: "Air Canada Flight 143, a Boeing 767 out of fuel, glided to a landing at Gimli, Manitoba, with no fatalities." },
      { y: 1999, k: "s", t: "Eileen Collins became the first woman to command a Space Shuttle mission as Columbia launched on STS-93." }],
    "07-24": [{ y: 1946, k: "m", t: "Bernard Lynch made the first live ejection from an aircraft in flight, using a Martin-Baker seat from a Gloster Meteor at 320 mph." },
      { y: 1969, k: "m", t: "Apollo 11 splashed down in the Pacific and the crew entered quarantine in a mobile isolation facility." },
      { y: 1975, k: "m", t: "The Apollo capsule landed after Apollo-Soyuz and the crew inhaled propellant fumes that entered the cabin; they were hospitalized in Honolulu." }],
    "07-25": [{ y: 1909, k: "a", t: "Louis Bleriot flew a monoplane across the English Channel from France to Dover." },
      { y: 1984, k: "s", t: "Svetlana Savitskaya became the first woman to perform a spacewalk, during a Salyut 7 mission." },
      { y: 2000, k: "a", t: "An Air France Concorde crashed after takeoff from Paris Charles de Gaulle, killing all 109 aboard and 4 on the ground." }],
    "07-26": [{ y: 1963, k: "s", t: "Syncom 2 was launched into the first geosynchronous orbit." },
      { y: 1971, k: "s", t: "Apollo 15 launched on the first Apollo J-class mission, carrying a lunar rover to the Moon." },
      { y: 2005, k: "s", t: "Discovery launched on STS-114, the first Space Shuttle flight after the Columbia accident." }],
    "07-27": [{ y: 1949, k: "a", t: "The de Havilland Comet 1, the first jet airliner prototype, made its first flight at Hatfield." }],
    "07-28": [{ y: 1973, k: "m", t: "Skylab 3 launched with a crew of three on what became a 59-day mission to study long-duration effects on the body." },
      { y: 1945, k: "a", t: "A B-25 bomber lost in fog struck the Empire State Building in New York." }],
    "07-29": [{ y: 1958, k: "s", t: "President Eisenhower signed the National Aeronautics and Space Act, which created NASA." },
      { y: 1985, k: "s", t: "Challenger launched on STS-51-F with Spacelab 2 and later reached orbit after an engine shut down early." }],
    "07-30": [{ y: 1971, k: "a", t: "A Japanese All Nippon Airways Boeing 727 collided with a fighter jet over Iwate, Japan, killing all 162 aboard the airliner." },
      { y: 2020, k: "s", t: "NASA launched the Perseverance rover toward Mars." }],
    "07-31": [{ y: 1901, k: "m", t: "Arthur Berson and Reinhard Suring ascended in a balloon to about 10,800 meters, using supplemental oxygen to counter altitude hypoxia." },
      { y: 1964, k: "s", t: "Ranger 7 struck the Moon after sending back the first close-up US images of the lunar surface." },
      { y: 1969, k: "s", t: "Mariner 6 flew past Mars and returned close-range images." }],
    "08-01": [{ y: 1943, k: "a", t: "US bombers carried out Operation Tidal Wave, a low-level raid on the oil refineries at Ploesti, Romania." }],
    "08-02": [{ y: 1985, k: "a", t: "Delta Air Lines Flight 191, a Lockheed L-1011, crashed short of the runway at Dallas-Fort Worth after flying into a microburst." },
      { y: 2020, k: "s", t: "The Crew Dragon Endeavour splashed down in the Gulf of Mexico, completing the first crewed orbital flight by a commercial spacecraft." }],
    "08-03": [{ y: 2004, k: "s", t: "NASA launched MESSENGER, the first spacecraft to orbit Mercury." }],
    "08-04": [{ y: 2007, k: "s", t: "NASA launched the Phoenix Mars Lander toward the northern polar region of Mars." }],
    "08-05": [{ y: 1969, k: "s", t: "Mariner 7 flew past Mars, passing about 3,500 kilometers from the surface." },
      { y: 2011, k: "s", t: "NASA launched the Juno spacecraft toward Jupiter." }],
    "08-06": [{ y: 1961, k: "m", t: "Gherman Titov flew Vostok 2 for a full day in orbit and reported nausea and disorientation, an early description of space motion sickness." },
      { y: 1945, k: "a", t: "The B-29 Enola Gay dropped an atomic bomb on Hiroshima." }],
    "08-07": [{ y: 1959, k: "s", t: "Explorer 6 was launched and later returned the first crude image of Earth taken from orbit." },
      { y: 1971, k: "s", t: "Apollo 15 splashed down in the Pacific after nearly 13 days." }],
    "08-08": [{ y: 1908, k: "a", t: "Wilbur Wright made his first public flight demonstrations in France at Le Mans." },
      { y: 2001, k: "s", t: "NASA launched the Genesis spacecraft to collect solar wind samples." }],
    "08-09": [{ y: 1945, k: "a", t: "A B-29, Bockscar, dropped an atomic bomb on Nagasaki after its primary target was obscured." }],
    "08-10": [{ y: 1966, k: "s", t: "Lunar Orbiter 1 launched and became the first US spacecraft to orbit the Moon." },
      { y: 1990, k: "s", t: "The Magellan spacecraft entered orbit around Venus to begin radar mapping." }],
    "08-11": [{ y: 1962, k: "s", t: "Andriyan Nikolayev was launched on Vostok 3, which flew for almost four days and, with Vostok 4, produced the first group spaceflight." }],
    "08-12": [{ y: 1960, k: "s", t: "NASA launched Echo 1, a large reflective balloon satellite used to bounce radio signals between ground stations." },
      { y: 1962, k: "s", t: "Pavel Popovich was launched on Vostok 4 and passed within a few kilometers of Vostok 3." },
      { y: 1985, k: "a", t: "Japan Air Lines Flight 123, a Boeing 747, crashed in the mountains after a failed rear pressure bulkhead repair led to loss of control." }],
    "08-13": [{ y: 1940, k: "a", t: "The German Luftwaffe began Adlertag, a major air offensive on British airfields during the Battle of Britain." }],
    "08-14": [{ y: 2005, k: "m", t: "Helios Airways Flight 522 crashed near Athens after loss of cabin pressure left the crew incapacitated by hypoxia." },
      { y: 1959, k: "s", t: "Explorer 6 transmitted a crude image of the sunlit Earth's cloud cover, the first picture of Earth from a satellite." }],
    "08-15": [{ y: 1935, k: "a", t: "Aviator Wiley Post and humorist Will Rogers died when their aircraft crashed near Point Barrow, Alaska." }],
    "08-16": [{ y: 1960, k: "m", t: "Joseph Kittinger jumped from a balloon at about 102,800 feet, setting records for the highest parachute jump and longest free fall." },
      { y: 1987, k: "a", t: "Northwest Airlines Flight 255, an MD-82, crashed after takeoff from Detroit when its flaps were not set." }],
    "08-17": [{ y: 1978, k: "a", t: "The balloon Double Eagle II landed in France, completing the first crossing of the Atlantic by balloon." }],
    "08-18": [{ y: 1932, k: "a", t: "Auguste Piccard and Max Cosyns reached about 16,200 meters in a pressurized balloon gondola launched from Switzerland." }],
    "08-19": [{ y: 1957, k: "m", t: "David Simons ascended in the Manhigh II balloon to over 100,000 feet and stayed aloft about 32 hours to study conditions relevant to spaceflight." },
      { y: 1960, k: "m", t: "Soviet dogs Belka and Strelka were launched on Korabl-Sputnik 2 and returned alive after a day in orbit." }],
    "08-20": [{ y: 1975, k: "s", t: "NASA launched Viking 1 toward Mars." },
      { y: 1977, k: "s", t: "NASA launched Voyager 2, which went on to fly past Jupiter, Saturn, Uranus and Neptune." }],
    "08-21": [{ y: 1965, k: "s", t: "Gemini 5 launched with Gordon Cooper and Charles Conrad for an eight-day mission." }],
    "08-22": [{ y: 1963, k: "a", t: "X-15 pilot Joseph Walker reached about 108 kilometers, the highest altitude flown by a winged aircraft at that time." },
      { y: 1985, k: "a", t: "A British Airtours Boeing 737 caught fire during takeoff at Manchester, and 55 people died, mostly from smoke inhalation." }],
    "08-23": [{ y: 1977, k: "a", t: "The human-powered Gossamer Condor, piloted by Bryan Allen, won the Kremer Prize by flying a figure-eight course." }],
    "08-24": [{ y: 1921, k: "a", t: "The airship R38 broke up over Hull, England, killing 44 of the 49 aboard." }],
    "08-25": [{ y: 1989, k: "s", t: "Voyager 2 made its closest approach to Neptune." },
      { y: 2003, k: "s", t: "NASA launched the Spitzer Space Telescope." }],
    "08-26": [{ y: 1978, k: "s", t: "Sigmund Jahn launched on Soyuz 31 and became the first German in space." }],
    "08-27": [{ y: 1783, k: "a", t: "Jacques Charles and the Robert brothers launched the first hydrogen balloon from the Champ de Mars in Paris." },
      { y: 1939, k: "a", t: "The Heinkel He 178 made the first flight of a turbojet-powered aircraft." },
      { y: 2006, k: "a", t: "Comair Flight 5191 crashed at Lexington, Kentucky, after the crew took off from a runway too short for the aircraft." }],
    "08-28": [{ y: 1988, k: "a", t: "Three jets of an Italian display team collided at Ramstein Air Base, Germany, and crashed into the crowd, killing 70 people." }],
    "08-29": [{ y: 1965, k: "m", t: "Gemini 5 landed after about eight days, a record then, showing that crews could tolerate flights as long as a Moon mission." }],
    "08-30": [{ y: 1983, k: "s", t: "Guion Bluford launched on STS-8 and became the first African American in space." },
      { y: 1984, k: "s", t: "Discovery launched for the first time on mission STS-41-D." }],
    "08-31": [{ y: 1986, k: "a", t: "Aeromexico Flight 498 collided with a private Piper over Cerritos, California, killing 82 people." }],
    "09-01": [{ y: 1979, k: "s", t: "Pioneer 11 became the first spacecraft to fly past Saturn." },
      { y: 1983, k: "a", t: "Korean Air Lines Flight 007 was shot down by a Soviet fighter after straying into Soviet airspace." }],
    "09-02": [{ y: 1998, k: "a", t: "Swissair Flight 111 crashed into the Atlantic off Nova Scotia after a fire began in the cockpit area." }],
    "09-03": [{ y: 1925, k: "a", t: "The US Navy airship USS Shenandoah broke apart in a storm over Ohio." },
      { y: 1976, k: "s", t: "Viking 2 landed on Mars on the Utopia Planitia plain." },
      { y: 2017, k: "s", t: "Peggy Whitson returned to Earth, ending a mission that gave her a US record of 665 cumulative days in space." }],
    "09-04": [{ y: 1936, k: "a", t: "Louise Thaden won the Bendix Trophy air race, with Blanche Noyes as co-pilot." }],
    "09-05": [{ y: 1862, k: "m", t: "James Glaisher lost consciousness during a high-altitude balloon ascent with Henry Coxwell, who opened the gas valve to descend." },
      { y: 1977, k: "s", t: "NASA launched Voyager 1." }],
    "09-06": [{ y: 1952, k: "a", t: "A de Havilland DH.110 broke up at the Farnborough air show, killing test pilot John Derry and 29 spectators." },
      { y: 1970, k: "a", t: "Militants hijacked several airliners in a coordinated operation that ended with aircraft destroyed at Dawson's Field in Jordan." }],
    "09-07": [{ y: 1956, k: "a", t: "Iven Kincheloe flew the Bell X-2 to about 126,000 feet, the first flight above 100,000 feet by a piloted aircraft." }],
    "09-08": [{ y: 1944, k: "s", t: "The first German V-2 rockets were fired at Paris and London." },
      { y: 2004, k: "s", t: "The Genesis sample capsule struck the Utah desert after its parachute failed to deploy." },
      { y: 2016, k: "s", t: "NASA launched OSIRIS-REx to collect a sample from asteroid Bennu." }],
    "09-09": [{ y: 1975, k: "s", t: "NASA launched Viking 2 toward Mars." }],
    "09-10": [{ y: 1976, k: "a", t: "Two airliners collided near Zagreb, Yugoslavia, killing 176 people, in a case linked to air traffic control workload and staffing." }],
    "09-11": [{ y: 2001, k: "a", t: "Four US airliners were hijacked and three struck buildings in New York and Washington, leading to a nationwide ground stop of civil aviation." }],
    "09-12": [{ y: 1962, k: "s", t: "President Kennedy delivered his Rice University speech committing the United States to a lunar landing." },
      { y: 1966, k: "s", t: "Gemini 11 launched with Pete Conrad and Richard Gordon and docked with an Agena on its first orbit." },
      { y: 1992, k: "s", t: "Mae Jemison became the first African American woman in space on STS-47, a Spacelab J mission with life sciences experiments." }],
    "09-13": [{ y: 1959, k: "s", t: "The Soviet Luna 2 probe crashed into the Moon, the first human-made object to reach another celestial body." }],
    "09-14": [{ y: 1966, k: "s", t: "Gemini 11 reached an apogee of about 1,370 kilometers, the highest Earth orbit of a crewed spacecraft to that time." }],
    "09-15": [{ y: 1968, k: "m", t: "The Soviet Zond 5 spacecraft launched toward the Moon carrying tortoises and other biological specimens." },
      { y: 2017, k: "s", t: "Cassini ended its mission by deliberately entering Saturn's atmosphere." }],
    "09-16": [{ y: 1996, k: "s", t: "Atlantis launched on STS-79 for the fourth Shuttle-Mir docking." }],
    "09-17": [{ y: 1908, k: "m", t: "Lt. Thomas Selfridge died of head injuries when a Wright Flyer crashed at Fort Myer, Virginia, the first fatality in a powered aircraft accident." },
      { y: 1976, k: "s", t: "NASA rolled out the first Space Shuttle orbiter, Enterprise." }],
    "09-18": [{ y: 1947, k: "a", t: "The United States Air Force was established as a separate service." },
      { y: 1980, k: "s", t: "Arnaldo Tamayo Mendez flew on Soyuz 38 and became the first Cuban and first Latin American in space." }],
    "09-19": [{ y: 1783, k: "m", t: "A sheep, a duck and a rooster were flown in a Montgolfier balloon at Versailles as the first living passengers, partly to test survival in the air." },
      { y: 1988, k: "s", t: "Israel launched its first satellite, Ofeq-1." }],
    "09-20": [{ y: 1992, k: "s", t: "Endeavour landed at Kennedy Space Center, ending STS-47." }],
    "09-21": [{ y: 1968, k: "m", t: "Zond 5 splashed down in the Indian Ocean, returning tortoises that were the first Earth animals to fly around the Moon." },
      { y: 2003, k: "s", t: "NASA's Galileo spacecraft was deliberately sent into Jupiter's atmosphere." }],
    "09-22": [{ y: 1980, k: "a", t: "Iraqi aircraft struck Iranian air bases at the start of the Iran-Iraq War." }],
    "09-23": [{ y: 1911, k: "a", t: "Earle Ovington carried mail by air at Garden City, New York, in the first official US airmail flight." },
      { y: 1913, k: "a", t: "Roland Garros made the first nonstop airplane flight across the Mediterranean Sea." },
      { y: 1999, k: "s", t: "Mars Climate Orbiter was lost during its orbit insertion after a unit mismatch in navigation software." }],
    "09-24": [{ y: 1929, k: "m", t: "Jimmy Doolittle flew a complete flight, including takeoff and landing, using instruments alone with a hooded cockpit." },
      { y: 1852, k: "a", t: "Henri Giffard flew a steam-powered airship about 27 kilometers near Paris." },
      { y: 2014, k: "s", t: "India's Mars Orbiter Mission entered orbit around Mars on its first attempt." }],
    "09-25": [{ y: 1973, k: "m", t: "The Skylab 3 crew splashed down after 59 days in orbit, then the longest US spaceflight." },
      { y: 1978, k: "a", t: "Pacific Southwest Airlines Flight 182 collided with a Cessna over San Diego, killing 144 people." },
      { y: 1992, k: "s", t: "NASA launched Mars Observer." }],
    "09-26": [{ y: 1983, k: "s", t: "The Soyuz T-10-1 crew escaped when their launch vehicle caught fire on the pad, in the only emergency use of a launch escape system on a crewed Soviet launch." },
      { y: 1996, k: "s", t: "Shannon Lucid returned on STS-79 after 188 days on Mir, then the longest spaceflight by a woman." },
      { y: 1997, k: "a", t: "Garuda Indonesia Flight 152 crashed near Medan, Indonesia, in smoky haze conditions." }],
    "09-27": [{ y: 1956, k: "a", t: "Milburn Apt reached Mach 3.2 in the Bell X-2 and then lost control, a flight in which he was killed." },
      { y: 2007, k: "s", t: "NASA launched the Dawn spacecraft to the asteroid Vesta and dwarf planet Ceres." }],
    "09-28": [{ y: 1924, k: "a", t: "Two Douglas World Cruisers landed in Seattle, completing the first aerial circumnavigation of the globe." }],
    "09-29": [{ y: 1977, k: "s", t: "The Soviet Union launched the Salyut 6 space station." },
      { y: 1988, k: "s", t: "Discovery launched on STS-26, the first Space Shuttle mission after the Challenger accident." }],
    "09-30": [{ y: 1968, k: "a", t: "Boeing rolled out the first 747 at its Everett, Washington factory." }],
    "10-01": [{ y: 1958, k: "s", t: "NASA began operations as the US civilian space agency, absorbing the National Advisory Committee for Aeronautics." }],
    "10-02": [{ y: 1990, k: "a", t: "A hijacked Xiamen Airlines Boeing 737 collided with two parked aircraft while landing at Guangzhou Baiyun airport, killing 128 people." }],
    "10-03": [{ y: 1967, k: "a", t: "Pete Knight flew the X-15A-2 to Mach 6.72, the highest speed ever reached by a crewed winged aircraft." },
      { y: 1962, k: "s", t: "Wally Schirra flew the six-orbit Mercury mission Sigma 7." },
      { y: 1942, k: "s", t: "The first A-4 (V-2) rocket launched successfully from Peenemunde and reached the edge of space." }],
    "10-04": [{ y: 1957, k: "s", t: "The Soviet Union launched Sputnik 1, the first artificial Earth satellite." },
      { y: 1959, k: "s", t: "The Soviet Union launched Luna 3, which later photographed the far side of the Moon." }],
    "10-05": [{ y: 1930, k: "a", t: "The British airship R101 crashed near Beauvais, France, on its first overseas flight, killing 48 of the 54 aboard." },
      { y: 1984, k: "s", t: "Space Shuttle Challenger launched on STS-41-G with seven crew members, including two women and the first Canadian astronaut." }],
    "10-06": [{ y: 1976, k: "a", t: "A bomb planted on Cubana Flight 455 exploded after takeoff from Barbados, and the DC-8 crashed into the sea, killing all 73 aboard." }],
    "10-07": [{ y: 1959, k: "s", t: "Luna 3 transmitted the first photographs of the far side of the Moon." }],
    "10-08": [{ y: 2001, k: "a", t: "An SAS MD-87 collided with a Cessna Citation on the runway in fog at Milan Linate, killing 118 people." }],
    "10-09": [{ y: 2009, k: "s", t: "NASA's LCROSS spacecraft and its spent Centaur stage were deliberately crashed into a lunar polar crater to search for water ice." }],
    "10-10": [{ y: 1967, k: "s", t: "The Outer Space Treaty entered into force, setting the basic legal framework for activities in space." }],
    "10-11": [{ y: 1968, k: "s", t: "Apollo 7 launched as the first crewed Apollo mission, an 11-day Earth-orbit test of the command and service module." },
      { y: 1984, k: "s", t: "Kathryn Sullivan became the first American woman to perform a spacewalk, during Shuttle mission STS-41-G." }],
    "10-12": [{ y: 1964, k: "m", t: "Voskhod 1 launched as the first spacecraft with a multi-person crew, carrying physician Boris Yegorov, the first doctor in space." }],
    "10-13": [{ y: 1972, k: "a", t: "A Uruguayan Air Force Fairchild FH-227 carrying a rugby team crashed in the Andes, and 16 of the 45 aboard survived 72 days in the mountains." }],
    "10-14": [{ y: 2012, k: "m", t: "Felix Baumgartner jumped from a balloon at about 39 km in a pressure suit and became the first person to exceed the speed of sound in freefall." },
      { y: 1947, k: "a", t: "Chuck Yeager flew the Bell X-1 faster than the speed of sound, the first confirmed supersonic level flight." }],
    "10-15": [{ y: 2003, k: "s", t: "Yang Liwei launched aboard Shenzhou 5 and became China's first astronaut." },
      { y: 1997, k: "s", t: "The Cassini-Huygens probe launched toward Saturn from Cape Canaveral." }],
    "10-16": [{ y: 1956, k: "a", t: "Pan Am Flight 6, a Boeing 377 Stratocruiser, ditched in the Pacific near a Coast Guard cutter after an engine failure, and all 31 aboard survived." },
      { y: 1910, k: "a", t: "The French airship Clement-Bayard II made the first airship crossing of the English Channel, flying from France to England." }],
    "10-17": [{ y: 1922, k: "a", t: "Lieutenant Virgil Griffin made the first takeoff from USS Langley, the US Navy's first aircraft carrier, in a Vought VE-7." }],
    "10-18": [{ y: 1967, k: "s", t: "The Soviet probe Venera 4 released its capsule into the atmosphere of Venus and returned data during its descent." },
      { y: 1989, k: "s", t: "Space Shuttle Atlantis launched the Galileo spacecraft toward Jupiter on STS-34." }],
    "10-19": [{ y: 1967, k: "s", t: "NASA's Mariner 5 flew past Venus at a distance of about 4,000 km." }],
    "10-20": [{ y: 1934, k: "a", t: "The MacRobertson Air Race from England to Australia began at RAF Mildenhall." }],
    "10-21": [{ y: 2020, k: "s", t: "Soyuz MS-16 landed in Kazakhstan, returning Chris Cassidy, Anatoly Ivanishin and Ivan Vagner after 196 days on the ISS." }],
    "10-22": [{ y: 1797, k: "a", t: "Andre-Jacques Garnerin made the first parachute descent from a balloon, jumping from about 900 m over Paris." },
      { y: 1968, k: "s", t: "Apollo 7 splashed down in the Atlantic after the first crewed Apollo flight." },
      { y: 1975, k: "s", t: "Venera 9 landed on Venus and sent back the first photographs from the surface of another planet." }],
    "10-23": [{ y: 2007, k: "s", t: "Space Shuttle Discovery launched on STS-120 to deliver the Harmony node to the International Space Station." }],
    "10-24": [{ y: 1946, k: "s", t: "A V-2 rocket launched from White Sands carried a camera that took the first photographs of Earth from high altitude." },
      { y: 1998, k: "s", t: "NASA launched Deep Space 1, a probe that tested ion propulsion and other new technologies." }],
    "10-25": [{ y: 2007, k: "a", t: "Singapore Airlines flew the first commercial passenger flight of the Airbus A380, from Singapore to Sydney." },
      { y: 1975, k: "s", t: "Venera 10 landed on Venus and transmitted data from the surface." }],
    "10-26": [{ y: 1958, k: "a", t: "Pan Am began Boeing 707 service across the Atlantic, flying New York to Paris with a stop at Gander." }],
    "10-27": [{ y: 1961, k: "s", t: "The first Saturn I rocket, SA-1, launched successfully from Cape Canaveral in a suborbital test." }],
    "10-28": [{ y: 1971, k: "s", t: "Britain's Prospero satellite launched on a Black Arrow rocket, the only British satellite launched by a British rocket." }],
    "10-29": [{ y: 1998, k: "m", t: "John Glenn, aged 77, launched on Space Shuttle Discovery on STS-95, which included studies of aging, sleep and bone loss in spaceflight." }],
    "10-30": [{ y: 1985, k: "s", t: "Space Shuttle Challenger launched on STS-61-A, the German Spacelab D1 mission and the last completed flight of Challenger." }],
    "10-31": [{ y: 2014, k: "m", t: "SpaceShipTwo broke up in flight over the Mojave Desert after the co-pilot unlocked the feather system early; the co-pilot was killed and the pilot survived." },
      { y: 1999, k: "a", t: "EgyptAir Flight 990 crashed into the Atlantic off Massachusetts, killing all 217 people aboard." }],
    "11-01": [{ y: 2011, k: "a", t: "LOT Polish Airlines Flight 16, a Boeing 767, landed safely at Warsaw without its landing gear extended, and all 231 aboard were uninjured." }],
    "11-02": [{ y: 1947, k: "a", t: "Howard Hughes flew the Hughes H-4 Hercules, known as the Spruce Goose, on its only flight, about one mile over Long Beach harbor." },
      { y: 2000, k: "s", t: "The first long-duration crew arrived at the International Space Station, beginning continuous human occupation of the station." }],
    "11-03": [{ y: 1957, k: "m", t: "The Soviet Union launched Sputnik 2 carrying the dog Laika, the first animal to orbit Earth." },
      { y: 1973, k: "s", t: "NASA launched Mariner 10, which became the first spacecraft to visit Mercury." }],
    "11-04": [{ y: 1959, k: "s", t: "NASA flew Little Joe 1A from Wallops Island, a test of the Mercury capsule launch escape system." }],
    "11-05": [{ y: 2013, k: "s", t: "India launched its Mars Orbiter Mission, its first interplanetary spacecraft." }],
    "11-06": [{ y: 1935, k: "a", t: "The prototype Hawker Hurricane made its first flight at Brooklands." },
      { y: 1958, k: "a", t: "The Bell X-1E made the last flight of the X-1 rocket plane series." }],
    "11-07": [{ y: 1910, k: "a", t: "Philip Parmelee flew a Wright Model B from Dayton to Columbus, Ohio, carrying silk in an early commercial air cargo flight." },
      { y: 1996, k: "s", t: "NASA launched Mars Global Surveyor toward Mars." }],
    "11-08": [{ y: 1950, k: "a", t: "A US Air Force F-80 pilot shot down a MiG-15 over Korea in the first air combat between jet aircraft." },
      { y: 2008, k: "s", t: "India's Chandrayaan-1 entered orbit around the Moon." }],
    "11-09": [{ y: 1967, k: "s", t: "The first Saturn V flew on the uncrewed Apollo 4 mission." },
      { y: 2005, k: "s", t: "The European Space Agency launched Venus Express." }],
    "11-10": [{ y: 1970, k: "s", t: "The Soviet Union launched Luna 17, carrying the Lunokhod 1 rover to the Moon." }],
    "11-11": [{ y: 1966, k: "m", t: "Gemini 12 launched with Buzz Aldrin, whose three spacewalks showed that extravehicular work was manageable with improved restraints and a slower pace." },
      { y: 1935, k: "a", t: "The Explorer II balloon reached 72,395 feet with Albert Stevens and Orvil Anderson aboard, a record altitude at the time." }],
    "11-12": [{ y: 1981, k: "s", t: "Space Shuttle Columbia launched on STS-2, the first reflight of a crewed orbital spacecraft." },
      { y: 2014, k: "s", t: "The Philae lander touched down on comet 67P, the first soft landing on a comet." }],
    "11-13": [{ y: 2009, k: "s", t: "NASA announced that the LCROSS impact had detected water ice in the lunar crater Cabeus." }],
    "11-14": [{ y: 1910, k: "a", t: "Eugene Ely flew a Curtiss pusher off a platform on the cruiser USS Birmingham, the first takeoff from a ship." },
      { y: 1969, k: "s", t: "Apollo 12 launched and was struck by lightning twice during ascent but reached orbit." },
      { y: 1971, k: "s", t: "Mariner 9 became the first spacecraft to orbit another planet when it entered orbit around Mars." }],
    "11-15": [{ y: 1967, k: "m", t: "X-15 pilot Michael Adams was killed when the aircraft entered a spin and broke up; the investigation cited distraction, vertigo and an electrical fault." },
      { y: 1988, k: "s", t: "The Soviet shuttle Buran made its only flight, an uncrewed two-orbit mission." }],
    "11-16": [{ y: 1973, k: "m", t: "Skylab 4 launched for an 84-day mission that gathered extensive data on bone, muscle and cardiovascular changes in long-duration spaceflight." },
      { y: 1974, k: "s", t: "The Arecibo radio telescope transmitted a short coded message toward the globular cluster M13." }],
    "11-17": [{ y: 1970, k: "s", t: "Lunokhod 1 landed on the Moon aboard Luna 17 and became the first robotic rover to operate on another world." }],
    "11-18": [{ y: 2013, k: "s", t: "NASA launched the MAVEN orbiter to study the upper atmosphere of Mars." }],
    "11-19": [{ y: 1969, k: "s", t: "Apollo 12 landed in the Ocean of Storms, close to the Surveyor 3 probe." }],
    "11-20": [{ y: 1998, k: "s", t: "The Zarya module launched from Baikonur as the first element of the International Space Station." }],
    "11-21": [{ y: 1783, k: "a", t: "Jean-Francois Pilatre de Rozier and the Marquis d'Arlandes made the first free flight in a hot-air balloon, crossing part of Paris." }],
    "11-22": [{ y: 1935, k: "a", t: "The Pan American China Clipper left Alameda, California, on the first transpacific airmail flight." },
      { y: 1977, k: "a", t: "British Airways and Air France began regular Concorde service between Europe and New York." }],
    "11-23": [{ y: 1996, k: "a", t: "Ethiopian Airlines Flight 961 was hijacked and ditched near the Comoros after running out of fuel, killing 125 of the 175 aboard." }],
    "11-24": [{ y: 1969, k: "s", t: "Apollo 12 splashed down in the Pacific, completing the second crewed lunar landing mission." },
      { y: 1971, k: "a", t: "A hijacker using the name Dan Cooper took over a Northwest Orient Boeing 727 and parachuted from it with ransom money." }],
    "11-25": [{ y: 1961, k: "a", t: "USS Enterprise, the first nuclear-powered aircraft carrier, was commissioned." }],
    "11-26": [{ y: 1965, k: "s", t: "France launched Asterix, its first satellite, on a Diamant rocket from Algeria." },
      { y: 2011, k: "s", t: "NASA launched the Mars Science Laboratory carrying the Curiosity rover." }],
    "11-27": [{ y: 1983, k: "a", t: "Avianca Flight 11 crashed on approach to Madrid, killing 181 of the 192 aboard." },
      { y: 1971, k: "s", t: "The Soviet Mars 2 lander crashed on Mars and became the first human-made object to reach the planet's surface." }],
    "11-28": [{ y: 1979, k: "m", t: "Air New Zealand Flight 901 flew into Mount Erebus in Antarctica in whiteout conditions after a navigation data change, killing all 257 aboard." },
      { y: 1983, k: "m", t: "Space Shuttle Columbia launched on STS-9 with Spacelab 1, carrying life science experiments and the first European payload specialist." },
      { y: 1964, k: "s", t: "NASA launched Mariner 4, which later made the first successful flyby of Mars." }],
    "11-29": [{ y: 1961, k: "m", t: "The chimpanzee Enos orbited Earth twice on Mercury-Atlas 5, testing the life support and physiological monitoring systems ahead of crewed orbital flight." },
      { y: 1967, k: "s", t: "Australia launched WRESAT, its first satellite, from Woomera." }],
    "11-30": [{ y: 1961, k: "a", t: "Ansett-ANA Flight 325, a Vickers Viscount, crashed into Botany Bay after takeoff from Sydney, killing all 15 aboard." }],
    "12-01": [{ y: 1783, k: "a", t: "Jacques Charles and Nicolas-Louis Robert made the first crewed flight in a hydrogen balloon, rising from the Tuileries in Paris." }],
    "12-02": [{ y: 1971, k: "s", t: "The Soviet Mars 3 lander made the first soft landing on Mars but stopped transmitting after about 15 seconds." },
      { y: 1990, k: "s", t: "Space Shuttle Columbia launched on STS-35 carrying the Astro-1 ultraviolet observatory." }],
    "12-03": [{ y: 1973, k: "s", t: "Pioneer 10 became the first spacecraft to fly past Jupiter." },
      { y: 1999, k: "s", t: "NASA lost contact with the Mars Polar Lander as it approached the surface of Mars." }],
    "12-04": [{ y: 1965, k: "m", t: "Gemini 7 launched for a 14-day flight, giving the first detailed data on the effects of two weeks of weightlessness on human crew members." },
      { y: 1959, k: "m", t: "Rhesus monkey Sam flew on the Little Joe 2 test for Project Mercury to study the biological effects of the flight." },
      { y: 1998, k: "s", t: "Space Shuttle Endeavour launched on STS-88 carrying the Unity node, the first US element of the International Space Station." }],
    "12-05": [{ y: 1945, k: "a", t: "Five US Navy TBM Avenger bombers of Flight 19 disappeared during a training flight from Fort Lauderdale." }],
    "12-06": [{ y: 1957, k: "s", t: "The first US attempt to launch a satellite, Vanguard TV3, exploded on the pad at Cape Canaveral." }],
    "12-07": [{ y: 1972, k: "s", t: "Apollo 17 launched at night from Kennedy Space Center on the last Apollo lunar mission." },
      { y: 1944, k: "a", t: "The Convention on International Civil Aviation was signed in Chicago, creating the framework for the later ICAO." },
      { y: 1995, k: "s", t: "The Galileo spacecraft arrived at Jupiter and released its atmospheric probe." }],
    "12-08": [{ y: 1963, k: "a", t: "Pan Am Flight 214, a Boeing 707, crashed near Elkton, Maryland, after a lightning strike, killing all 81 aboard." }],
    "12-09": [{ y: 1978, k: "s", t: "The four Pioneer Venus probes entered the atmosphere of Venus and sent back data on the way down." }],
    "12-10": [{ y: 1963, k: "m", t: "Chuck Yeager ejected from an NF-104A after it entered a flat spin at the top of a zoom climb and was injured by burns from the ejection seat." }],
    "12-11": [{ y: 1972, k: "s", t: "Apollo 17 landed in the Taurus-Littrow valley with Eugene Cernan and Harrison Schmitt, a geologist." },
      { y: 1998, k: "s", t: "NASA launched the Mars Climate Orbiter, which was later lost at Mars because of a units error." }],
    "12-12": [{ y: 1961, k: "s", t: "OSCAR 1, the first amateur radio satellite, was launched." },
      { y: 1985, k: "a", t: "Arrow Air Flight 1285, a DC-8 carrying US soldiers, crashed after takeoff from Gander, killing all 256 aboard." }],
    "12-13": [{ y: 1962, k: "s", t: "NASA launched Relay 1, an early active communications satellite." }],
    "12-14": [{ y: 1962, k: "s", t: "Mariner 2 flew past Venus, the first successful planetary flyby by a spacecraft." },
      { y: 1972, k: "s", t: "Apollo 17 lifted off from the Moon, the most recent time humans have left the lunar surface." }],
    "12-15": [{ y: 1965, k: "s", t: "Gemini 6A launched and made the first crewed space rendezvous with Gemini 7." },
      { y: 1970, k: "s", t: "Venera 7 made the first soft landing on another planet and transmitted from the surface of Venus." }],
    "12-16": [{ y: 1960, k: "a", t: "A United Airlines DC-8 and a TWA Super Constellation collided over New York, and the DC-8 crashed in Brooklyn, killing 134 people." }],
    "12-17": [{ y: 1903, k: "a", t: "Orville and Wilbur Wright made the first powered, controlled airplane flights at Kitty Hawk, North Carolina." },
      { y: 1935, k: "a", t: "The Douglas DC-3 made its first flight in Santa Monica." }],
    "12-18": [{ y: 1965, k: "m", t: "Gemini 7 landed after 14 days in orbit, completing the longest spaceflight to that date and providing key data on prolonged weightlessness in humans." },
      { y: 1958, k: "s", t: "The US launched Project SCORE, the first communications satellite to relay a voice message from orbit." }],
    "12-19": [{ y: 1972, k: "s", t: "Apollo 17 splashed down in the Pacific, ending the Apollo lunar program." }],
    "12-20": [{ y: 1995, k: "a", t: "American Airlines Flight 965 flew into a mountain on approach to Cali, Colombia, after a navigation error, killing 159 of the 163 aboard." },
      { y: 2019, k: "s", t: "Boeing's Starliner launched on its first uncrewed orbital flight test." }],
    "12-21": [{ y: 1968, k: "s", t: "Apollo 8 launched on the first crewed flight to the Moon." },
      { y: 1988, k: "a", t: "A bomb destroyed Pan Am Flight 103 over Lockerbie, Scotland, killing 270 people." }],
    "12-22": [{ y: 1964, k: "a", t: "Lockheed test pilot Bob Gilliland flew the first SR-71 Blackbird from Palmdale, California." }],
    "12-23": [{ y: 1986, k: "a", t: "Voyager, piloted by Dick Rutan and Jeana Yeager, landed at Edwards Air Force Base after the first nonstop flight around the world without refueling." }],
    "12-24": [{ y: 1968, k: "s", t: "Apollo 8 entered lunar orbit, and the crew took the Earthrise photograph." },
      { y: 1979, k: "s", t: "The first Ariane rocket launched from Kourou, French Guiana." }],
    "12-25": [{ y: 2021, k: "s", t: "The James Webb Space Telescope launched on an Ariane 5 from French Guiana." }],
    "12-26": [{ y: 1973, k: "s", t: "Soyuz 13 landed after an eight-day mission with two cosmonauts that carried an ultraviolet telescope." }],
    "12-27": [{ y: 1968, k: "s", t: "Apollo 8 splashed down in the Pacific, completing the first crewed flight to the Moon." }],
    "12-28": [{ y: 1978, k: "m", t: "United Airlines Flight 173 ran out of fuel and crashed near Portland while the crew dealt with a landing gear problem, a case that shaped crew resource management." },
      { y: 2014, k: "a", t: "AirAsia Flight 8501 crashed into the Java Sea, killing all 162 people aboard." }],
    "12-29": [{ y: 1972, k: "m", t: "Eastern Air Lines Flight 401 crashed in the Florida Everglades while the crew was distracted by a burned-out landing gear indicator light, killing 101 people." }],
    "12-30": [{ y: 1907, k: "m", t: "William Randolph Lovelace II was born; he later developed aviation oxygen equipment and chaired NASA's advisory committee on life sciences." }],
    "12-31": [{ y: 1968, k: "a", t: "The Tupolev Tu-144 made its first flight, becoming the first supersonic airliner to fly." }],
  };
});
